version: "3.8"

services:
  app:
    image: php:8.3-fpm-alpine
    container_name: ecoride_app

    volumes:
      - uploads_data:/var/www/html/public/uploads
    networks:
      - proxy
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "mysql://ecoride:tonmdp@mariadb:3306/ecoride"
      MONGODB_URL: "mongodb://root:Azote355538@mongo:27017"
      APP_SECRET: "ta_clé_ultra_secrète_prod"
    restart: unless-stopped

volumes:
  uploads_data:

networks:
  proxy:
    external: true
