version: "3.8"

services:
  app:
    build: .
    image: ecoride
    container_name: php

    volumes:
      - uploads_data:/var/www/html/app/uploads
      - ./app/public/build:/var/www/html/public/build:ro
      - ./php-conf/zzz-listen-tcp.conf:/usr/local/etc/php-fpm.d/zzz-listen-tcp.conf:ro

    networks:
      proxy:
        aliases:
          - php              

    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET: 
      DATABASE_URL: 
      MONGODB_URL: 

    restart: unless-stopped
  messenger_worker:
    build: .
    image: ecoride
    container_name: messenger_worker
    command: php bin/console messenger:consume async --time-limit=3600
    volumes:
      - uploads_data:/var/www/html/app/uploads
      - ./app/public/build:/var/www/html/public/build:ro
      - ./php-conf/zzz-listen-tcp.conf:/usr/local/etc/php-fpm.d/zzz-listen-tcp.conf:ro
    networks:
      proxy:
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      APP_SECRET:
      DATABASE_URL: 
      MONGODB_URL: 
    restart: unless-stopped

volumes:
  uploads_data:

networks:
  proxy:
    external: true

