

services:
  php:
    build: ./docker/php
    container_name: ecoride_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:1.25-alpine
    container_name: ecoride_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:10.11
    container_name: ecoride_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql

  #mongo:
    #image: mongo:7
    #container_name: ecoride_mongodb
    #ports:
      #- "27017:27017"
    #volumes:
      #- mongo_data:/data/db

volumes:
  db_data:
  mongo_data: