app = "ecoride"  # Nom que Fly.io te proposera ou que tu choisis

primary_region = "cdg"  # Paris

[build]
  dockerfile = "docker/php/Dockerfile"

[env]
  APP_ENV = "prod"
  APP_DEBUG = "0"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
