# fly.toml
app = "ecoride-white-moon-1925"
primary_region = "cdg"

[build]
  dockerfile = "docker/php/Dockerfile"

[env]
  APP_ENV   = "prod"
  APP_DEBUG = "0"

[deploy]
  release_command = "php /var/www/html/bin/console doctrine:migrations:migrate --no-interaction --env=prod"

[[services]]
  internal_port = 80
  protocol      = "tcp"
  processes     = ["app"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port     = 80
    handlers = ["http"]

[[checks]]
  type          = "http"
  name          = "http-check"
  interval      = "15s"
  timeout       = "2s"
  grace_period  = "10s"
  method        = "get"
  path          = "/"
  protocol      = "http"

[[vm]]
  memory    = "1gb"
  cpu_kind  = "shared"
  cpus      = 1
