# fly.toml app configuration file generated for ecoride-white-moon-1925 on 2025-05-27T18:11:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecoride-eco'
primary_region = 'cdg'

[build]
  dockerfile = 'docker/php/Dockerfile'

[deploy]
  release_command = 'php /var/www/html/bin/console doctrine:migrations:migrate --no-interaction --env=prod'

[env]
  APP_DEBUG = '0'
  APP_ENV = 'prod'

[[mounts]]
  source = 'uploads'
  destination = '/var/www/html/public/uploads'

[[services]]
  protocol = 'tcp'
  internal_port = 80
  processes = ['app']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.http_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'get'
    path = '/'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
