# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    trusted_proxies: ['0.0.0.0/0', '::/0']
    trusted_headers: ['x-forwarded-for', 'x-forwarded-port', 'x-forwarded-proto', 'x-forwarded-host']
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: 
        handler_id: null
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
